apiVersion: v1
kind: Pod
metadata:
    name: two-containers
spec:
    restartPolicy: Never

    volumes:
        - name: shared-data
          emptyDir: {}

    containers:
        - name: writer
          image: writer
          volumeMounts:
              - name: shared-data
                mountPath: /vol
          imagePullPolicy: IfNotPresent
          command:
              - zx
          args:
              - writer.mjs
              - --loop-up-to
              - "200"

        - name: reader
          image: reader
          volumeMounts:
              - name: shared-data
                mountPath: /vol-reader
                readOnly: true
          imagePullPolicy: IfNotPresent
          command:
              - zx
          args:
              - --quiet
              - reader.mjs
              - --wait-for-writer-iteration
              - "180"
