apiVersion: v1
kind: Pod
metadata:
    name: two-containers
spec:
    restartPolicy: Never

    volumes:
        - name: shared-data
          emptyDir: {}

    containers:
        - name: writer
          image: writer
          volumeMounts:
              - name: shared-data
                mountPath: /vol

        - name: reader
          image: reader
          volumeMounts:
              - name: shared-data
                mountPath: /vol-reader
